### ISSUE TITLE
Early access or development branch?

### ISSUE THREAD

**Issue by llonca13** [linuxserver/docker-ombi#1]
Is there a way to choose these other branches ? (i need Early acces to test emby integration,i dont use plex).
If no is it possible to add it?
Thanks
P.s. sorry I posted empty post by mistake. Both :)

**Comment by sparklyballs** [comment]
is this a question or a request ?

**Comment by sparklyballs** [comment]
there are no plans currently to offer development or EAP branches
and it isn't possible in this image at least to change branch, unless it is something that can done via the webui.

**Comment by llonca13** [comment]
its possible in the web gui but when the app restarts it reverts back.
I understand.Thanks
