### ISSUE TITLE
Add support for base url

### ISSUE THREAD

**Issue by fswings** [linuxserver/docker-ombi#10]
In the old plexrequests container there was support for a base url using environment variable.  The same approach does not appear to work.  I tried adding `-e RUN_OPTS="-base /ombi"` as per ombi docs but it didn't work.

**Comment by webvictim** [comment]
+1

**Comment by thelamer** [comment]
@fswings @webvictim 

This is baked into ombi no need for an external setting: 

![ombibase](https://user-images.githubusercontent.com/1852688/34803620-0f7e5ece-f629-11e7-9244-8f95ca01ae78.png)

**Comment by webvictim** [comment]
Yeah - was just looking for a way to set it at container create time rather
than having to set it up manually, but I guess it does save the setting
after you do it once.
