### ISSUE TITLE
Auto-Update on startup?

### ISSUE THREAD

**Issue by nodiaque** [linuxserver/docker-ombi#100]
Hello,

I was wondering if the container couldn't auto-update the app on startup like some other container does? Right now, my ombi installation says there's a new version, but this won't install unless this container get updated. Would be great if a simple reboot could update it instead of waiting on a human intervention.

Thank you!

**Comment by j0nnymoe** [comment]
We won't be doing auto update on start up for our containers as it goes against the point of using containers.
