### ISSUE TITLE
Update to v4.21.0 from 4.16.12

### ISSUE THREAD

**Issue by ElanHasson** [linuxserver/docker-ombi#102]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Should have latest version v4.21.0

## Current Behavior
Has old version, 4.16.12

**Comment by ElanHasson** [comment]
Hey @aptalca thanks for pointing that out-- I should have been clearer that I'm using the `latest` tag, shouldn't that always be the latest version regardless of the tag version?

**Comment by j0nnymoe** [comment]
@ElanHasson they're develop/pre-releases - latest we use to track stable releases and develop tracks the pre-releases.

**Comment by ElanHasson** [comment]
Thanks for clarifying.
