### ISSUE TITLE
Outdated Ombi - Latest Version: v4.28.0

### ISSUE THREAD

**Issue by sgtcoder** [linuxserver/docker-ombi#109]
## Expected Behavior
The latest version should be compiled routinely and provided to us as a Docker

## Current Behavior
A very old buggy version is provided to us from August 5th, v4.22.5

## Steps to Reproduce
Simply use the latest version from linuxserver/docker-ombi

## Environment
**OS:** AlmaLinux 8.6/RHEL
**CPU architecture:** x86_64
**How docker service was installed:**
Given your docker compose

## Command used to create docker container (run/create/compose/screenshot)
Let me know if you really need.

## Docker logs
Let me know if you really need.

**Comment by Roxedus** [comment]
It is not outdated, there has not been a stable release from Ombi since August, just pre-releases, which are considered as development releases.

**Comment by sgtcoder** [comment]
> It is not outdated, there has not been a stable release from Ombi since August, just pre-releases, which are considered as development releases.

Thank you for the clarification. They have so many "pre-releases" tagged as releases and when you goto their About Page it says their are updates to the stable. Either way, you seem to be correct as far as their master branch goes.

I am just going to use the development releases then.
