### ISSUE TITLE
Ombi doesn't load, acting as if href path isn't set in head section of index

### ISSUE THREAD

**Issue by jimmyhiggs337** [linuxserver/docker-ombi#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on page load I see a white page and receive this error message in the console:  "The stylesheet [my ip]/styles.f699774fe28f5b1b.css was not loaded because its MIME type, “text/html”, is not “text/css”."

it appears to be happening because a tag is missing form the head of the angular app like in this issue:
https://stackoverflow.com/questions/2190459/the-stylesheet-was-not-loaded-because-its-mime-type-text-html-is-not-text-c

### Expected Behavior

ombi home page will load

### Steps To Reproduce

open ombi's webpage

### Environment

```markdown
- OS: truenas scale 22.02.4
- How docker service was installed: via truecharts docker compose app running portainer (I also tried running the native ombi truecharts app that runs this docker image)
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
      - /mnt/Files/compose/ombi/config(old):/config
    ports:
      - '3759:3579'
    restart: unless-stopped
  mysql_db:
    image: "mysql:5.7"
    container_name: ombi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Mygirl337
    volumes:
      -  /mnt/Files/compose/ombi/mysql(old):/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ombi_phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: mysql_db
      ports:
        - '7081:80'
      depends_on:
        - "mysql_db"
```

### Container logs

```bash
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[custom-init] No custom files found, skipping...
Hello, welcome to Ombi
Valid options are:
Ombi 4.22.5
Copyright (C) 2022 Ombi
  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.
  --storage    Storage path, where we save the logs and database
  --baseurl    The base URL for reverse proxy scenarios
  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...
  --migrate    Will run the migrations then exit the application
  --help       Display this help screen.
  --version    Display version information.
Base Url: /ombi
Wrote new baseurl at /app/ombi/ClientApp/dist/index.html
We are running on http://*:3579
i

[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
Have you tried adding `/ombi` to the end of your url you're using?

**Comment by jimmyhiggs337** [comment]
> Have you tried adding `/ombi` to the end of your url you're using?

yes, I get a response time out, it isn't pushing to the /ombi path

**Comment by jimmyhiggs337** [comment]
I can confirm it's running, I am still receiving pushbullet notifications, I just can't get to the web ui

**Comment by j0nnymoe** [comment]
Could be a networking issue on truenas then?

Just to confirm, the container itself does work: https://ci-tests.linuxserver.io/linuxserver/ombi/latest/index.html

Problem is, no one within the team uses nor do we test against truenas scale so I suspect it's something to do which how that works that's causing your issue. 

Might be worth hitting up the TrueCharts people to see why?

**Comment by jimmyhiggs337** [comment]
> Could be a networking issue on truenas then?
> 
> Just to confirm, the container itself does work: https://ci-tests.linuxserver.io/linuxserver/ombi/latest/index.html
> 
> Problem is, no one within the team uses nor do we test against truenas scale so I suspect it's something to do which how that works that's causing your issue.
> 
> Might be worth hitting up the TrueCharts people to see why?

update I can get to the webui, the truenas app is not working, but the portainer version is, as you can see in the config has 3759 set as the address, I was trying to access my truenas app version at 3579 and didn't realize.
