### ISSUE TITLE
[BUG] Unusual issue when using in k8s

### ISSUE THREAD

**Issue by Xander-Rudolph** [linuxserver/docker-ombi#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm running the ombi image inside a k8s cluster, and I mount the volume, it sets the appropriate path but when I run the pod, I get the following error:

```
chown: changing ownership of '/config': Operation not permitted
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
chown: changing ownership of '/config': Operation not permitted
s6-rc: warning: unable to start service init-ombi: command exited 1
```

When I inspect the mount from inside the pod, I can see that it has the following permissions:
`drwxrwxrwx 1 1026 users    0 Apr  8 23:54 config`

None of my other linuxserver images have an issue with the config mount, just the ombi image.

Even when passing the securityContext.runAsUser or runAsGroup set to 0, the pod runs as root, however the /config path is still using PUID 1026 and the group users

### Expected Behavior

When mounting to /config the permissions should not be denied... I'm not sure how the other images manage the /config but ombi appears to be different.

### Steps To Reproduce

1. Install a form of k8s (microk8s, docker desktop k8s, minikube, rancher desktop k8s {disable traefik if using rancher}, etc)
2. use the install instructions here: https://github.com/Xander-Rudolph/mediakube-redux/tree/main/charts/mediakube#linuxmac

### Environment

```markdown
- OS: rancher-desktop running on windows 11
- How docker service was installed: helm chart
```

### CPU architecture

x86-64

### Docker creation

```bash
using the default docker image: lscr.io/linuxserver/ombi
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

chown: changing ownership of '/config': Operation not permitted
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
chown: changing ownership of '/config': Operation not permitted
```
```

**Comment by aptalca** [comment]
We don't support or recommend config folders on remote shares. As reported in the log, you are using the image in an unsupported fashion and therefore I'm closing this issue. Feel free to ask the community in our discord if you have further questions.
