### ISSUE TITLE
[FEAT] Auto Adjust Sidebar to fit Application Name

### ISSUE THREAD

**Issue by GeekStreetSolutions** [linuxserver/docker-ombi#112]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have my Ombi Application Name as "Plex Requests". The issue is that the S in Requests gets pushed to the line below. I would like to be able to have the side bar auto adjust to fit the full word and not split words off into two.
![Screenshot (222)](https://github.com/linuxserver/docker-ombi/assets/8231094/2a6f36ea-8729-4431-8508-32c90d3f8546)

### Reason for change

Fixes issues where Application title does not fit on sidebar, causing it to wrap around to the next line.

**Comment by Roxedus** [comment]
Not a container issue. Report directly to ombi
