### ISSUE TITLE
[BUG] Old version

### ISSUE THREAD

**Issue by fizzy6868** [linuxserver/docker-ombi#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

is there any chance you could update to latest v4.46.1 as the mobile app does not work with current thanks

### Steps To Reproduce

try using app says server to old

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
used unraid defaults
```

### Container logs

```bash
none
```

**Comment by j0nnymoe** [comment]
They're pre releases. Once ombi does a proper release, the main tag for this image will be updated. If you need to use the pre-release, use the `:development` tag.

**Comment by Roxedus** [comment]
We have built and pushed the latest stable release
https://github.com/linuxserver/docker-ombi/releases/tag/v4.44.1-ls200
4.46.1 is a beta, which we also have built https://github.com/linuxserver/docker-ombi/releases/tag/development-v4.46.1-ls404

**Comment by fizzy6868** [comment]
> We have built and pushed the latest stable release https://github.com/linuxserver/docker-ombi/releases/tag/v4.44.1-ls200 4.46.1 is a beta, which we also have built https://github.com/linuxserver/docker-ombi/releases/tag/development-v4.46.1-ls404

sorry i have over looked this thanks.
