### ISSUE TITLE
[Feature] Add support for Ombi v3 Open Beta

### ISSUE THREAD

**Issue by rickatnight11** [linuxserver/docker-ombi#12]
Ombi's v3 is in open beta, and since it's a complete rewrite that won't support upgrading existing v2 databases, it'd be great to have a separate image tag built against this new version for testing and upgrade preparation.

As per Ombi's Github README, downloads are available here:

https://ci.appveyor.com/project/tidusjar/requestplex/branch/DotNetCore/artifacts

Notably v3 is built against .NET Core, no longer depending on Mono.

**Comment by aptalca** [comment]
We already have a build in the works (hint: the preview branch here). It needs some internal testing before it is opened up, but we are working with the developers of ombi

**Comment by rickatnight11** [comment]
Thanks, @aptalca!  Could we keep this issue open until the branch is merged and the feature is available?  That way I'll get notified!

**Comment by aptalca** [comment]
Sure we can keep it open in the meantime so others can see as well.

**Comment by evanrich** [comment]
where's the preview branch?  don't see a link by the "here"

**Comment by aptalca** [comment]
The preview image is available here for testing: https://hub.docker.com/r/lsiodev/ombi-preview/

It does not use, update or touch the v2 database. It creates a brand new one with a different name, so one should be able to go back if they choose to. One would also have to set it up from scratch going from v2 to v3

**Comment by yeyeoke** [comment]
Anyone using the V3 container and gotten updates to work? the auto-updater fails to kill the process, I'm new to docker and not very experienced yet. I'm sorry if this is the wrong place to ask but I couldn't figure out any other.

**Comment by aptalca** [comment]
@yeyeoke

Just restart the container

**Comment by EnorMOZ** [comment]
Just tried this yesterday and it seems to get stuck on the "Loading" screen. Nothing useful in the logs. 

Tried using the following in docker with nginx-proxy. I saw that the default --host is http://*:5000 now. Not sure if that has anything to do with it. 

```
- "127.0.0.1:3579:3579"

VIRTUAL_HOST: "ombi.{{domain}}"
 VIRTUAL_PORT: 3579```

**Comment by tidusjar** [comment]
@EnorMOZ The default is 5000 when not supplied, but the docker supplies that parameter. 

If you restart your docker for it to update to the latest version it should now work, I have put a temp fix in place until the Angular team fix the issue.

**Comment by After-Shock** [comment]
Just seeing if there's an update on a v3 public container?  I'm trying to get the devs over at cloud box to drop Plex requests and use v3 based container.  Thanks in advance.

**Comment by danmandle** [comment]
@sparklyballs Why was this issue closed? Is there a public V3 container?

**Comment by sparklyballs** [comment]
there is a preview version available as per @aptalca's comments
