### ISSUE TITLE
"Something went wrong!" - until searching

### ISSUE THREAD

**Issue by ZackEndboss** [linuxserver/docker-ombi#15]
Dear linuxserver-Community,

first of all, nice work.
but i've an issue with my ombi build.

**Setup:**
Docker: linuxserver/ombi docker-build
Application Version: 2.2.1678
System Version: 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)
Branch: Stable & Dev.
Log Level: Trace
HOST: Debian (Docker: 17.05.0-ce)
HOST: Windows (Docker: 17.06.2-ce)
Configured: Only sonarr
Browser tested: Firefox, Chrome

**Doing:**
Configured a Sonarr.
- Test Connectivity: "Connected to Sonarr successfully!"

If i send the request (tv-show), i get:
"Something went wrong!" no matter which season im requesting

**Local:**
I've copied the files out of the container and started it without issues on my local windows machine. Looks like it's something with the docker-image. (same configured sonarr and plex)
Same Issue occurred on my windows docker host system (17.06.2-ce).

**Logging:**
I can just find the request/response for the search:
Ombi.Api.ApiRequest Trace: Request made to http://api.tvmaze.com/search...

But nothing more.
Some ideas how to find the Issue?

**Comment by ZackEndboss** [comment]
nc shows that there is no request going out to sonarr.

**good case:** on windows without docker:
```
user@host:~$ docker run -ti --rm -p 8182:8182 chilcano/netcat:jessie -vvl -p 8182
->>>>>> (Executing '/bin/netcat -vvl -p 8182') <<<<<<-
listening on [any] 8182 ...
clientip: inverse host lookup failed: Unknown host
connect to [dockerip] from (UNKNOWN) [clientip] 52582
GET /api/series HTTP/1.1
X-Api-Key: <myipkey>
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/105.2.3.0
Host: hostip:8182
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
```

**Bad Case:** on ombi inside docker no request was received on nc

until that i installed netcat inside the docker container except connection-issues with docker.
Same result - netcat: no request.

**Comment by sparklyballs** [comment]
post your run commands for both ombi and sonarr

and the url you're using in ombi to connect to sonarr with

**Comment by ZackEndboss** [comment]
**Ombi:**
docker create \
    --name=ombi \
    -v /etc/localtime:/etc/localtime:ro \
    -v /home/user/config/ombi-dev:/config \
    -e PGID=1000 -e PUID=1000 \
    -e TZ='Europe/Berlin' \
    -p 3579:3579 \
    linuxserver/ombi

**sonarr:**
docker create \
	--name sonarr \
	-p 8989:8989 \
	-e PGID=1000 -e PUID=1000  \
	-v /etc/localtime:/etc/localtime:ro \
	-v /home/user/Downloads:/downloads \
	-v /home/user/config/sonarr/config:/config \
	-v /home/user/sonarr/tv:/tv \
	linuxserver/sonarr

in ombi settings:
ip: domain and ip (both tested)
port: 8989

The sonarr-connection-settings i used in the ombi-docker are the same i used to test in ombi on windows and plexrequest. (to check if it's working outside docker)
But there are a bunch of other combinations i tested also like a second sonarr on my local machine to exclude that the issue would be there or the nc thing inside the ombi-container or a sonarr with a nginx-proxy. All let me come to the same guess it's the ombi-build.

No idea how to get to the heart of the Problem. I wish there are more tracelogs

**Comment by sparklyballs** [comment]
the "cause" is something to do with the newer version of mono that was pulled in last weeks image refresh of the baseimage this image is built from

have retagged :56 as the latest version and put a hold on building newer versions until one of the has spoken to ombi dev

**Comment by aptalca** [comment]
Just so you know, ombi v3 is in the works, so v2 is no longer developed.

We have a beta image for v3 here available for testing: https://hub.docker.com/r/lsiodev/ombi-preview/

Keep in mind that it uses a new database scheme so you would have to start over with the settings and such, and that this app updates itself on container start since it is beta and there are frequent releases.
