### ISSUE TITLE
Bootstrap generated files not saving to set url base

### ISSUE THREAD

**Issue by Caedis** [linuxserver/docker-ombi#19]
Host OS: unRAID 6.4.0_rc18f
[Container Template](https://imgur.com/v2sewVv)

Web Server: Letsencrypt docker by Linuxserver

[Nginx config](https://pastebin.com/9SpHztU6)

Issue:
[Bootstrap is generating a file and saves it to the root of the site.](https://imgur.com/IHJT9DJ)

Notes:

- [Site when accessed through reverse proxy](https://imgur.com/5A1Jirh)
- [How it should be mapping](https://imgur.com/UT9EU4p)
- Going to https://[DOMAIN]/ombi/dist/2.js shows the javascript file
- Ombi is set to use the /ombi base url
- Going to [IP]:3579/ombi shows it correctly and is working with no issues

**Comment by Caedis** [comment]
Wait...this probably makes more sense to post on the Ombi V3 github....i am an idiot

**Comment by aptalca** [comment]
Yup, this is not docker related and belongs on the ombi repo

**Comment by Caedis** [comment]
Yep, Fix is related to nginx
[Link for anyone who has this issue](https://github.com/tidusjar/Ombi/wiki/Nginx-Reverse-Proxy-examples-(Linux))
