### ISSUE TITLE
New upstream platform-specific release URLs

### ISSUE THREAD

**Issue by Neo-Desktop** [linuxserver/docker-ombi#21]
Hello,

Starting in release tag [Ombi v3.0.2881](https://github.com/tidusjar/Ombi/releases/tag/Ombi-v3.0.2881)

It appears the generic "ombi.zip" is being phased out.

It doesn't look like the Dockerfile build script will be able to handle this automagically and will need to be updated.

Thanks, LinuxServer.io! You are the best!

**Comment by aptalca** [comment]
We have a different branch and a build for v3
https://github.com/linuxserver/docker-ombi/blob/preview/Dockerfile#L25
https://hub.docker.com/r/lsiodev/ombi-preview/
