### ISSUE TITLE
Still getting Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied.

### ISSUE THREAD

**Issue by Fish2** [linuxserver/docker-ombi#28]
I am still getting this error 
Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. - Permission denied

I have delete and re pulled this image and also clear ombi config but still get this error 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04.4 LTS
 
`docker create --name=ombi --network=fish_network --restart=always -v /docker/containers/ombi/config:/config -v /docker/certs/selfsigned:/certs -e TZ=Europe/London -e PGID=1000 -e PUID=1000 -p 3579:3579/tcp linuxserver/ombi`

**Comment by sparklyballs** [comment]
this is non-standard 

-v /docker/certs/selfsigned:/certs

take that out and see if it is the culprit

**Comment by Fish2** [comment]
That worked how strange i add this to all my container incase i need to use the certs any idea why this affects ombi ?

**Comment by sparklyballs** [comment]
no idea 

closing this as not a container issue
