### ISSUE TITLE
Server crashes on some specific search terms

### ISSUE THREAD

**Issue by rochdev** [linuxserver/docker-ombi#32]
When doing a search, sometimes the server simply crashes and the process restarts. This only seems to happen for some keywords but not others. For example, in TV Shows, I can successfully search for `the good doctor` but when searching for `house` the problem occurs.

Here is the information about my system:

Host OS: `Synology DSM 6.1.6-15266 Update 1`
Kernel: `Linux diskstation 4.4.15+ #15266 SMP PREEMPT Mon Mar 26 15:09:23 CST 2018 x86_64 GNU/Linux synology_apollolake_918+`

Run command:

```sh
docker create \
    --name=ombi \
    --restart always \
    --network=host \ # temporary
    --dns 8.8.8.8 \
    --dns 8.8.4.4 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /volume4/docker/ombi:/config \
    -e PGID=100 -e PUID=1034  \
    -p 3579:3579 \
    linuxserver/ombi
```

Memory usage:

```
              total        used        free      shared  buff/cache   available
Mem:        7990024     1031280     1729076       70692     5229668     6509632
Swap:       6889388      184900     6704488
```

The only log entry I can see is the new process starting after the previous one crashes:

```
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3334-develop
...
```

Please let me know if there is any log level setting I can set to gather more information.

**Comment by rochdev** [comment]
It seems to be related to the size of the Plex library somehow. I've imported a lot of series and now nearly all searches result in a crash.

**Comment by homerr** [comment]
Looks as if this issue may have been upstream and is now resolved.
