### ISSUE TITLE
Old build with broken update system

### ISSUE THREAD

**Issue by Adrimau** [linuxserver/docker-ombi#36]
Hi! I'm running Docker on my NAS Synology DS918+ and I've just installed Ombi with your Docker container.
Your container install the build 3.0.3111 of the branch master. According to the developer, this build has a problem with the update system so I can't upgrade to the last version (3.0.3477).

<img width="781" alt="image" src="https://user-images.githubusercontent.com/31062488/42938752-a4a13e6c-8b53-11e8-9202-68cd69d44184.png">

It would be great if you could change your container with the last master build, with a functional update system.

Thanks!

**Comment by j0nnymoe** [comment]
Ombi trigger a rebuild of our container when they release a new build. There was a new built pushed last night it seems, please make sure you are atleast running version 105 of our container. You can check this with the commands in the readme.

**Comment by Adrimau** [comment]
I've just installed Ombi today, it's strange that I have the version 77. How can I update the container?

**Comment by j0nnymoe** [comment]
Delete you container and any relating images then pull :latest

**Comment by sconnery** [comment]
I cannot update on 

3.0.4036
--

"  at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Update(PerformContext c) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.c
ne 239                                                                                                                                                   
fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]                                                                                                    
      Exception thrown in the OmbiUpdater, see previous messages                                                                                         
System.ComponentModel.Win32Exception (2): No such file or directory                                                                                      
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean re
ctStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)      
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)                                                                                   
   at System.Diagnostics.Process.Start()                                                                                                                 
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Update(PerformContext c) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.c
ne 239      "

**Comment by j0nnymoe** [comment]
> Delete you container and any relating images then pull :latest

**Comment by sconnery** [comment]
but then ill need to rebuild it everytime there is a update? I have configured it .

**Comment by j0nnymoe** [comment]
Yep, this is how docker works.

**Comment by sconnery** [comment]
but whats the point of the update feature? It works on tautilli

**Comment by aptalca** [comment]
@sconnery if you mapped the config folder correctly, your settings should persist.

**Comment by aptalca** [comment]
Whether it works or not, it's a feature of the app, not the container or the docker image. We do not support updating apps inside containers.

**Comment by sconnery** [comment]
Was not aware of the below (new to docker)

That worked Im prettysure.

Thank you

**Comment by thelamer** [comment]
@sconnery you can use docker to update images to avoid compose or saving your run commands also. 

This will work for you in the future if you find the need: 
```
sudo docker run --rm \
-v /var/run/docker.sock:/var/run/docker.sock taisun/updater \
--oneshot <Your Container Names>
```
