### ISSUE TITLE
Ombi crashes on start for docker version 121

### ISSUE THREAD

**Issue by btrebbien** [linuxserver/docker-ombi#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Linux Mint Cinammon

sudo docker create -h ombi --name=ombi -v /etc/localtime:/etc/localtime:ro -v /home/path/to/config:/config -e PGID=1000 -e PUID=1000 -e TZ=America/New_York -p 3579:3579 linuxserver/ombi

We are running on 

Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
Parameter name: revision
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at System.Environment.<>c.<.cctor>b__79_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Ombi.Program.BuildWebHost(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 114
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3795-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list 
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the 
               specified port and protocol (for example, http://*:5000). The 
               protocol (http:// or https://) must be included with each URL. 
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.

We are running on

**Comment by homerr** [comment]
Is this issue persistent with the latest version pulled from linuxserver/ombi? I have not long set this up, without issue.

**Comment by thelamer** [comment]
I cannot reproduce this , please pull and run if you are still having a problem. 
```
docker pull linuxserver/ombi:latest
```

**Comment by mandreko** [comment]
I think this is still an issue. I've pulled latest from docker, but it's happening to me too. 

The core of the issue appears to be this: https://github.com/tidusjar/Ombi/issues/1924

It's been fixed in the Ombi code-base, but not packaged as part of an actual release. Since linuxserver's Ombi Dockerfile looks at the latest release, and not latest commit, it'll be present in this docker container until Ombi makes a new release.

**Comment by thelamer** [comment]
@mandreko we provide a "development" tag if you want to run closer to head. This builds their pre-releases currently at "3.0.4183"
