### ISSUE TITLE
Sonarr linking - no quality profiles or root folders

### ISSUE THREAD

**Issue by jefftr66** [linuxserver/docker-ombi#43]
Ubuntu 18.04
Ombi in Docker 

Can't see anything in pull down menus - Load buttons just endlessly spin
Not sure what to put in host - just putting name of container has worked best in other links

![screenshot from 2019-01-24 16-42-59](https://user-images.githubusercontent.com/46849235/51717830-5f6ef080-1ff7-11e9-8cb2-df5a61b620dc.png)
[ombilog.txt](https://github.com/linuxserver/docker-ombi/files/2794194/ombilog.txt)

**Comment by thelamer** [comment]
@jefftr66 Please head over to our discord for stuff like this, you might be able to find a community user that can help you out with this issue. 

https://discord.gg/YWrKVTn

I want to emphasize to you that we maintain the Docker Logic for packaging these applications and delivering them on Dockerhub, you will have a much better chance with specific application issues on a social platform for that specific application, you can also find Ombis discord link at the bottom of this page: 
https://ombi.io/

**Comment by jefftr66** [comment]
Thanks!
