### ISSUE TITLE
CPU spiking every minute

### ISSUE THREAD

**Issue by mhbates** [linuxserver/docker-ombi#49]
Running version 3.0.4256. I noticed that this is spiking the CPU every minute, exactly, about 15-20%, specifically iowait according to Netdata (so not really a CPU spike per se, but you get the picture). This stops once the container is stopped. I checked Ombi's cron jobs section and didn't see anything scheduled to run every minute. Has anyone else encountered this?

**Comment by aptalca** [comment]
Nothing in the docker. It's really question for the ombi devs
