### ISSUE TITLE
Request: configure baseurl via environment variable

### ISSUE THREAD

**Issue by yannouchou** [linuxserver/docker-ombi#55]
As mentioned in #6 the ombi command supports passing a baseurl as argument.
It would be very convenient to be able to set this up via an environment variable, which should be fairly straightforward to implement, and very useful of course for proxy users.

I understand that this setting can be set via the UI, but obviously this requires first having access to the UI on the root domain, which in some scenarios might be impractical.

**Comment by aptalca** [comment]
I generally don't like to create env variable options for settings that exist in the gui. Because once you set that variable, the gui setting will no longer work as it will get overridden by the env variable.

I'll give it some more thought

**Comment by yannouchou** [comment]
I see your point.
For me this kind of setting should really be a startup parameter and should not be in the UI (if you change it the UI stops working). But since it is in the UI, I understand the confusion.
I don't actually know what the application behavior is if both the cmd argument and the UI setting are specified...

**Comment by tobbenb** [comment]
Doesn't the UI work still, if you use the correct baseurl?
