### ISSUE TITLE
Lets Encrypt Mail Server Certificate not trusted

### ISSUE THREAD

**Issue by FingerlessGlov3s** [linuxserver/docker-ombi#56]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 18.04

ombi:
    image: linuxserver/ombi
    container_name: ombi
    depends_on:
      - vpn-dns
    environment:
      - PUID=60001
      - PGID=60001
      - TZ=Europe/London
    dns:
      - 192.168.20.80
    volumes:
      - /mnt/docker/ombi/data/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

I think updating certificate store or adding in lets encrypts root ca should fix this I would imagination.

**Comment by mueslo** [comment]
also united domains smtp server appears untrusted.

**Comment by aptalca** [comment]
@mueslo report upstream: https://packages.ubuntu.com/bionic/ca-certificates
