### ISSUE TITLE
Unable to set base url

### ISSUE THREAD

**Issue by josevh** [linuxserver/docker-ombi#6]
I'm running this behind a reverse proxy and would like to use `/ombi` to access ombi.
However, on page load, I get redirected to `/wizard` instead of `/ombi/wizard`.
There is no setting to set the base url.

Currently the docker image mentioned the [ombi](https://github.com/tidusjar/Ombi#docker) repo, uses an environment variable to pass the run options to the executable that allows setting the base url.

[Link](https://github.com/rogueosb/docker-plexrequestsnet)

`-e RUN_OPTS="-base /ombi"`

Would it be possible to do something similar? Is it already possible?

I am not familiar with writing docker scripts unfortunately.

**Comment by tidusjar** [comment]
Hey, you should only be hitting the /wizard/ URL on the first load of Ombi. After that you should never see it. Can you complete the wizard and then try?

**Comment by CHBMB** [comment]
There's a setting in the webui to alter the base URL after you set it up.  No need for any environmental variables.

**Comment by josevh** [comment]
To be clear, accessing ombi was no issue when local. However for a completely remote install I wouldn't be able to access ombi except by exposing the port or setting the reverse proxy to access ombi at the root of the domain rather than a subdirectory.

**Comment by aptalca** [comment]
If you're trying to set it up while connected remotely, you can either set it up (initially) as a subdomain and then you can revert to the base url method. Or, you can use a vpn while you're setting it up.
