### ISSUE TITLE
Reverse Proxy - LetsEncrypt with 4.0.4728

### ISSUE THREAD

**Issue by ados8** [linuxserver/docker-ombi#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

UnRAID Version: 6.7.2

Complete fresh install of docker app to try and eliminate any possible contamination
Other apps are working with the proxy and before upgrading the stable build was fine. When trying to access the page internally no issue but externally it loads to a blank page. Based on my config this indicates Ombi is attempting to load but the data is not able to be displayed.

Current setting in Nginx

#Ombi
location /ombi/ {
    proxy_pass http://192.168.0.2:3579;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  90;
    proxy_redirect http://192.168.0.2:3579 https://$host;
}

**Comment by ados8** [comment]
Tested for hours and seems to be an issue with reverse proxy only. NAT forwarding to test IP works without SSL as expected.
Tried forcing HTTP through and same blank page so SSL not the issue but I believe its a bug within the build as this results on the proxy load only:

/ombi
please-wait.js:1 Uncaught SyntaxError: Unexpected token <
(index):35 Uncaught TypeError: window.pleaseWait is not a function
    at (index):35
runtime.741402d1d47331ce975c.js:1 Uncaught SyntaxError: Unexpected token <
polyfills.07404388c75b0a5fb465.js:1 Uncaught SyntaxError: Unexpected token <
scripts.578f0b3351d1fc5e26cf.js:1 Uncaught SyntaxError: Unexpected token <
main.3fb50b2d6b31f22be01b.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by aptalca** [comment]
This is the preset proxy conf our letsencrypt image uses: https://github.com/linuxserver/reverse-proxy-confs/blob/master/ombi.subfolder.conf.sample

**Comment by ados8** [comment]
Thanks but still was not able to get it working, reverted back to latest stable build and instantly everything working.

**Comment by aptalca** [comment]
v4 builds exist only for the ombi dev team for their internal development. We don't list that tag in the readme as it is not meant for public consumption (I believe it is in alpha stage). If the ombi team asked you to do testing for them, please report any issues upstream to ombi.
