### ISSUE TITLE
Memory Usage High

### ISSUE THREAD

**Issue by vinaykapadia** [linuxserver/docker-ombi#62]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
My RancherOS VM is using dynamic memory, and it just balloons to crazy sizes (over 10gb, which is really high for this OS). Eventually I lose access to the VM and Ombi doesn't respond to requests, until I hard restart the VM. I run "top" on the VM and it shows Ombi is using over 5gb of memory by itself. Line in top is:

```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 6442  6438 sshd     S    5312m 278%   0% /opt/ombi/Ombi --storage /config --host http://*:3579
```

Host OS is RancherOS running in VM on Hyper-V on Windows Server 2019 on bare metal.
Created using docker-compose, yml is:
ombi:
  image: linuxserver/ombi
  container_name: ombi
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Los_Angeles
  volumes:
    - /path/to/config/folder:/config
  restart: unless-stopped
  networks:
    - traefik_proxy
  labels:
    - "a bunch of labels to enable traefik to route to this"
    - "if these are of interest, let me know and i'll post them"

**Comment by aptalca** [comment]
Memory leaks should be reported to upstream.

In the meantime, you can look into limiting memory for the container: https://docs.docker.com/config/containers/resource_constraints/
