### ISSUE TITLE
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

### ISSUE THREAD

**Issue by simonk83** [linuxserver/docker-ombi#7]
Lots of frequent crashes with the latest version, logs say:

`* Assertion: should not be reached at sgen-scan-object.h:90`

(massive stacktrace omitted)

```Debug info from gdb:
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
```

Running on a Synology DiskStation.

**Comment by ethanopp** [comment]
+1 QNAP container station

**Comment by jkaberg** [comment]
@sparklyballs pretty sure this is due to the mono version (5.0.1.1), I'm now running another container with mono 4.6.2.16 which works just fine.

I noticed that only 5.0.1.1 is available from alpine repo.

**Comment by sparklyballs** [comment]
@jkaberg this image doesn't use alpine, it's based on ubuntu xenial.

**Comment by jkaberg** [comment]
ah right my bad. anyhow just letting you know in case you want to downgrade (or upgrade) 😄

**Comment by cron410** [comment]
Also seeing this issue on RancherOS

**Comment by MrBlaTi** [comment]
Also having that issue on Arch

**Comment by enchained** [comment]
I'm also having this, on Synology DSM 6. Could anyone suggest any solution, please? It's basically unusable right now in this state. 

Ombi says mono version is 5.2.0.224 (tarball Tue Oct 3 19:49:47 UTC 2017). Tried to install mono 4.6.2.16 in the same container, but had no luck. Not sure how to better run this in another container with a different mono version, cause have not much experience with docker.

@sparklyballs any thoughts?

**Comment by aptalca** [comment]
May not be the solution you expect, but ombi 3 is currently in beta, doesn't use mono and will replace the mono version soon. You might want to switch now: https://hub.docker.com/r/lsiodev/ombi-preview/

**Comment by cron410** [comment]
That's what I switched to for compatibility with Organizr.

**Comment by enchained** [comment]
Thanks! I was wary of the "do not use" warning, but at least that one works.

**Comment by CHBMB** [comment]
Container no longer based on mono.  Going to close this.

**Comment by rochdev** [comment]
I get exactly the same behaviour using Ombi 3.0.3330 in Docker.

The image I use is `linuxserver/ombi:91`.

**Comment by rochdev** [comment]
Just tried with `lsiodev/ombi-preview:53` which uses the `develop` branch for good measure, and I get the same behaviour.

**Comment by rochdev** [comment]
(I meant to post that in #9 actually so the behaviour I'm talking about is the server crashing after a search)

**Comment by aptalca** [comment]
@rochdev those are mono errors. How are getting exactly the same errors in the latest when it's no longer mono based? Post your logs

**Comment by CHBMB** [comment]
@rochdev Please explain how I my post above you when I closed the issue states that it's no longer based on mono how you're seeing the exact same issue, which was a problem with the mono version, when there's no mono in the image.

If you want to submit an issue, fine, but please use the template we provide and fill in all the information.  If you don't we can't fix/look at it and we'll just close the issue.
