### ISSUE TITLE
Ombi not loading on iPhones with HTTP basic auth reverse nginx proxy

### ISSUE THREAD

**Issue by clifford64** [linuxserver/docker-ombi#71]
Describe the bug
The web interface doesn't seem to work with iPhones. I can login, but cannot see any pictures, previous requests, search for anything, view any settings or anything like that. I have tried Safari and chrome. The web interface works normally without issues on my Galaxy note 9 using chrome and on desktop computers. This only seems to happen when using http basic auth through nginx reverse proxy. When I turn off basic auth, it works fines. 

Posted on ombi thread https://github.com/tidusjar/Ombi/issues/2880

To Reproduce

Go to ombi web interface
Login
Can't do anything while on an iPhone
Expected behavior
It works perfectly fine on my Android phone and desktop computers.

Screenshots
I have not been able to take screen shots.

Logs (Logs directory where Ombi is located)
If applicable, a snippet of the logs that seems relevant to the bug if present.

Desktop (please complete the following information):

OS: Windows 10, Android 9.0 pie, iPhone iOS 12
Ombi Version (please complete the following information):

Version 3.0.5202
Media Server Plex
Additional context
I currently use http basic auth for initial authentication so I can hide the website from public eyes

**Comment by tobbenb** [comment]
If it's only a problem on iPhone, then it's not a problem with this container. Probably should be fixed by Apple?

**Comment by clifford64** [comment]
> If it's only a problem on iPhone, then it's not a problem with this container. Probably should be fixed by Apple?

I wouldn't say that. It works if I turn http basic auth off. So I am trying to track down if it is an issue with the container, or the nginx reverse proxy conf from letsencrypt.
