### ISSUE TITLE
Using HTTPS?

### ISSUE THREAD

**Issue by Vinnpinn** [linuxserver/docker-ombi#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

Is it possible to force https? When the Container starts up it tells you that you need to use the -host option and specify if you want to use http or https. Is it possible to change the default http setting to https?

**Comment by aptalca** [comment]
Not in this container. We recommend reverse proxying: https://docs.linuxserver.io/general/swag
