### ISSUE TITLE
Item added to Retry Queue  - OMBI and RADARR v3

### ISSUE THREAD

**Issue by gregbert42** [linuxserver/docker-ombi#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When Movies are added to 
------------------------------

## Steps to Reproduce

1. User uses ombi to request a movie
2. I receive email that says:
Hello! The user 'XYZ' has requested "a movie" but it could not be added. This has been added into the requests queue and will keep retrying
3. The movie is anyway added to radarr
4. the user is not notified when the movie becomes available

## Environment
Docker 19.03.13 on linux, amd64
Ombi 3.0.5223-master
Radarr: 3.0.1.4259-ls91 by linuxserver.io

## Command used to create docker container (run/create/compose/screenshot)

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - TZ="Europe/Zurich"
      - PGID=1002
      - PUID=1002
    volumes:
      - /home/remote_fs_user/conf/ombi/:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - proxy

## Docker logs
http://sprunge.us/hrXyo8
(please forgive the mild redaction)

**Comment by Roxedus** [comment]
Not a container issue. However it's solved in ombi v4
