### ISSUE TITLE
Failed to create CoreCLR, HResult: 0x80070008

### ISSUE THREAD

**Issue by Jmanhale1** [linuxserver/docker-ombi#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Ombi should start up automatically and run its service.

## Current Behavior
Ombi doesn't start up. look into the logs and i get this error: Failed to create CoreCLR, HRESULT: 0x80070008

## Steps to Reproduce
1. Stopped docker container for ombi using portainer.
2. Started docker container for ombi using portainer.
3. View logs and they look as described below.

## Environment
**OS:** Ubuntu 18.04.6, Linux 5.4.0-109-generic Kernel
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
using plexguide currently (working on trying to find a new solution) utilizing official github source.

## Docker logs
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008

**Comment by chiefo0306** [comment]
Saw the same thing on Unraid. Rolling back to linuxserver/ombi:v4.16.12-ls119 allows for successful runs

**Comment by kje1** [comment]
Same issue here. Also reverted to linuxserver/ombi:v4.16.12-ls119 which is operating as expected

**Comment by j0nnymoe** [comment]
https://docs.linuxserver.io/faq#jammy

This link will explain the issue being experienced here and tell you how to fix.

**Comment by chiefo0306** [comment]
Got it, so basically looks like you can't upgrade the docker on Unraid unless you update to 6.10 RC6 (released today, included docker 20.10.14) or it will break.

**Comment by chiefo0306** [comment]
Just updated to Unraid 6.10 RC6 and switched back to latest on the ombi docker. Like @j0nnymoe mentioned, this resolved it.
